# Buildpacks to include in builder
[[buildpacks]]
id = "tanzu-buildpacks/java-lite"
version = "9.18.0"
uri = "tanzu-build.packages.broadcom.com/tanzu-java-buildpack/java-lite:9.18.0"

[[buildpacks]]
id = "samples/hello-extensions"
version = "0.0.1"
uri = "../buildpacks/hello-extensions"

# Order used for detection (buildpacks)
[[order]]
    [[order.group]]
        id = "tanzu-buildpacks/java-lite"
        version = "9.18.0"

# Base images used to create the builder
[build]
image = "tanzu-build.packages.broadcom.com/tanzu-base-ubuntu-2204-stack/build:0.1.114"
[run]
[[run.images]]
image = "tanzu-build.packages.broadcom.com/tanzu-base-ubuntu-2204-stack/run:0.1.114"
